# Generated by Django 5.0.2 on 2025-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiapp1', '0002_rename_meta_description_result_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='meta_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='apply_date',
            new_name='exam_date1',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='og_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='og_image_alt',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='meta_keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='vacancy_name',
            new_name='vacancy_info',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancy_title',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam_date1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam_date2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam_date3',
        ),
        migrations.AddField(
            model_name='job',
            name='exam_date2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='exam_date3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='post_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
