# Generated by Django 5.0.2 on 2025-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiapp1', '0004_alter_job_online_application_date_alter_result_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
