# Generated by Django 5.0.2 on 2025-06-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifiapp1', '0007_admission_status_admitcard_status_answerkey_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='vacancy_details',
            new_name='admission_details',
        ),
        migrations.AddField(
            model_name='admission',
            name='Counseling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='Merit_list_released',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='download_course_list_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
