# Generated by Django 5.0.2 on 2025-06-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifiapp1', '0008_rename_vacancy_details_admission_admission_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='vacancy_details',
            new_name='subject_details',
        ),
    ]
